spring:
  application:
    name: shop-main
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: consumerGroupId

  datasource:
    url: jdbc:mysql://localhost:3306/jinheung_client_proxy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  redis:
    host: localhost
    port: 6379
server:
  port: 8084
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
services:
  user-service: http://localhost:8084