spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: shop-main
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AuthFilterFactory
  redis:
    host: localhost
    port: 6379
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://3.38.254.90:8761/eureka/
routes:
  user-service:
    base-uri: http://localhost:8082
  client-proxy-sockjs:
    base-uri: http://localhost:8084
cloud:

